#!/usr/bin/php
[?php

/*
 * This file is part of the Lime framework.
 *
 * (c) Fabien Potencier <fabien.potencier@symfony-project.com>
 * (c) Bernhard Schussek <bernhard.schussek@symfony-project.com>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

<?php if (isset($relativeLimeDir)): ?>
require_once dirname(__FILE__).'<?php echo DIRECTORY_SEPARATOR.$relativeLimeDir.DIRECTORY_SEPARATOR.'lib'.DIRECTORY_SEPARATOR ?>LimeAutoloader.php';
<?php else: ?>
require_once '<?php echo $absoluteLimeDir.DIRECTORY_SEPARATOR.'lib'.DIRECTORY_SEPARATOR ?>LimeAutoloader.php';
<?php endif ?>
LimeAutoloader::register();

$cli = new LimeCli();
exit($cli->run(isset($argv) ? $argv : array()));
