#!/usr/bin/php
[?php

/*
 * This file is part of the Lime framework.
 *
 * (c) Fabien Potencier <fabien.potencier@symfony-project.com>
 * (c) Bernhard Schussek <bernhard.schussek@symfony-project.com>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

require_once '<?php echo $limeDir.DIRECTORY_SEPARATOR.'lib'.DIRECTORY_SEPARATOR ?>LimeAutoloader.php';
LimeAutoloader::register();

$cli = new LimeCli();
return $cli->run(isset($argv) ? $argv : array());
